### ISSUE TITLE
master branch generates develop.cfg without Zopeskel

### ISSUE THREAD

**Issue by albieback** [plone/plonedev.vagrant#11]
Steps to reproduce:

1 - Dowload plonedev.vagrant from master
2 - vagrant up at the master dir
3 - Check at plone/develop.cfg

Even though the docs (readme at root of the repository, and the comments in develop.cfg) mention zopeskel, there is no part.

The docs (readme and comment in develop.cfg) never mention mr.bob.

Standards change to fast for documentation to follow :-)

**Comment by smcmahon** [comment]
mr.bob replaces zopeskel in this installer release. Bad references fixed. Thanks!
