### ISSUE TITLE
Several plonedev.vagrant in the same machine

### ISSUE THREAD

**Issue by albieback** [plone/plonedev.vagrant#13]
QUESTION: How to use plonedev.vagrant to create more than one development environment (one for Plone 4.3.6 and another for master, for example)?

Dunno if it is relevant, but I am using Windows 7, and I am able to use a single plonedev.vagrant environment successfully.

**Comment by smcmahon** [comment]
The community discussion list is probably a better place to ask a question, as it allows many more people to see it.

I suspect the only problem would be that -- if unchanged -- the multiple VMs would be trying to attach to the same ports on the host. You may change port assignments by editing the Vagrant config file, then restarting the VM. On Windows, you'll also need to make sure that your SSH program (probably PuTTy) is then connecting on the matching port.

If you don't actually need them running at the same time, just halt the VMs when you're not using them.
