### ISSUE TITLE
Vagrant install completed without problems, VirtualBox instance is running, but commands won't work

### ISSUE THREAD

**Issue by hmnelson** [plone/plonedev.vagrant#16]
After running plonedev.vagrant I seem to have a running VirtualBox instance which I can ssh into using vagrant ssh, but when I try to follow the next steps in the documentation at https://github.com/plone/plonedev.vagrant/tree/5.0, all I get is this:

[pmmlt22:~/Desktop/Plone5/plonedev.vagrant-master] hmnelson% buildout
buildout: Command not found.
[pmmlt22:~/Desktop/Plone5/plonedev.vagrant-master] hmnelson% plonectl fg
plonectl: Command not found.

I'll freely admit that I'm an ignoramus when it comes to the command line, so I don't doubt that I'm doing something wrong. I'd really appreciate a pointer to what it might be, though.  :-)

**Comment by hmnelson** [comment]
If it makes a difference, I'm on a MacBook Pro (17-inch, late 2011) with a 2.4 GHz Intel Core i7, running Mac OS X 10.11.2

**Comment by hmnelson** [comment]
I read the issue about "Symlinks aren't built on second vagrant up", and since I'd done one "vagrant up," then destroyed it, then did another up, I thought perhaps that was what my problem was.

So I destroyed my VirtualBox, deleted the plonedev.vagrant-master directory, and just for good measure, uninstalled Vagrant. I then re-installed Vagrant, unzipped a fresh copy of plonedev.vagrant-master, and tried "vagrant up" again.

Same result—I have a running plonedev VirtualBox, I can ssh into it, but the commands don't work, and Plone isn't running on it. Frustrating.  :-/

**Comment by hmnelson** [comment]
Progress! This worked:

[pmmlt22:~/Desktop/Plone5/plonedev.vagrant-master] hmnelson% ./plonectl.sh fg

It failed if I left out either the ./ or the .sh. Is this something that I am just supposed to know (if I actually knew my way around a terminal window), or should the instructions (which leave those details out) correct and there's something weird about my environment?

**Comment by smcmahon** [comment]
The instructions for those commands are written for Windows users. Will fix!

**Comment by hmnelson** [comment]
Thanks!
